### PR TITLE
This fixed the Issue #2 without using exceptions.

### PR DESCRIPTION
**Pull request by khorsmann**
This fixed the Issue #2 without using exceptions. 
@rrauenza

### CODE REVIEW

**Comment by mback2k** [comment]
Please squash the commits into a single commit that contains the 3 line changes. Thanks.

**Comment by khorsmann** [comment]
Hi Marc, i will do this hopefully today. Thanks for answering.

**Comment by khorsmann** [comment]
Hi Marc, i rebased my commits and squashed it like you request it.

**Comment by mback2k** [comment]
Hi Karsten, thanks, I will merge it tomorrow after testing it with some of my local pfSense configurations.

**Comment by mback2k** [comment]
Thanks, I merged this pull-request manually.

**Pull request closed without merging**
